name: CI Pipeline   # A friendly name for the workflow

# When should this CI run?
on:
  push:             
    branches: [ "main" ]
  pull_request:    
    branches: [ "main" ]

jobs:
  build:            
    runs-on: ubuntu-latest  

    steps:
      # Step 1: Pull your repo code into that VM
      - uses: actions/checkout@v3

      # Step 2: Install JDK (Java Development Kit 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   
          java-version: '17'

      # Step 3: Build backend with Maven (compile + package)
      - name: Build Backend with Maven
        working-directory: ./backend
        run: mvn -B clean install

      # Step 4: Run backend tests (JUnit)
      - name: Run Backend Tests
        working-directory: ./backend
        run: mvn test