name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: portfolio_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=rootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..12}; do
            if mysql -h 127.0.0.1 -P 3306 -u root --password=rootpass -e "SELECT 1" >/dev/null 2>&1; then
              echo "✅ MySQL is up!"
              break
            fi
            echo "⏳ Waiting for MySQL... ($i/12)"
            sleep 5
            if [ $i -eq 12 ]; then
              echo "❌ MySQL did not become available in time"
              exit 1
            fi
          done

      - name: Verify MySQL connection and database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root --password=rootpass -e "SHOW DATABASES;"
          mysql -h 127.0.0.1 -P 3306 -u root --password=rootpass -e "USE portfolio_db; SELECT 'Database is ready' as status;"

      - name: Build with Maven
        run: |
          cd server
          mvn -B clean verify -Dspring.profiles.active=test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/portfolio_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpass