name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: portfolio_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -prootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..12}; do
            if mysql -h mysql -P 3306 -uroot -prootpass -e "SELECT 1" >/dev/null 2>&1; then
              echo "✅ MySQL is up!"
              exit 0
            fi
            echo "⏳ Waiting for MySQL... ($i/12)"
            sleep 5
          done
          echo "❌ MySQL did not become available in time"
          exit 1

      - name: Build with Maven
        run: mvn -B clean verify